"use client";

import { useEffect, useState } from "react";
import { Bot, Check, CircleAlert, Crown, Save } from "lucide-react";
import type { Project, ProjectTreeNode } from "../../../../types/dcode";
import styles from "../project-environment.module.css";

const serverUrl = "http://localhost:5283";
type Section = "overview" | "agents";
type Agent = { id:string; projectId:string; name:string; role:string; instructions:string; browserProfileId:string|null; providerType:string|null; accountName:string|null; model:string|null; enabled:boolean; isLead:boolean; updatedUtc:string };
type Account = { id:string; providerType:string; transport:string; name:string; connected:boolean };

export function ProjectManagement({ project, tree, initialSection = "overview", embedded = false }: { project: Project; tree: ProjectTreeNode[]; initialSection?: Section; embedded?: boolean }) {
  const [section,setSection]=useState<Section>(initialSection);
  return <main className={`${styles.management} ${embedded ? styles.embeddedSurface : ""}`}>{!embedded ? <header><span>Project management</span><h1>{project.name}</h1><p>Configure the project identities that will eventually own conversations, runs, and delegated work.</p></header> : null}{!embedded ? <nav>
    <button className={section==="overview"?styles.active:""} onClick={()=>setSection("overview")}>Overview</button>
    <button className={section==="agents"?styles.active:""} onClick={()=>setSection("agents")}>Agents</button>
    {["Models & Providers","Tool permissions","Usage","Integrations","Sync","Danger zone"].map(item=><button key={item} disabled>{item}<small>Later</small></button>)}
  </nav> : null}{section==="overview"?<Overview project={project} tree={tree}/>:<Agents projectId={project.id}/>}</main>;
}

function Overview({project,tree}:{project:Project;tree:ProjectTreeNode[]}) { const stack=detectStack(tree); return <div className={styles.managementGrid}><section><label>Identity</label><dl><div><dt>Name</dt><dd>{project.name}</dd></div><div><dt>Local path</dt><dd>{project.path}</dd></div><div><dt>Description</dt><dd>Not set</dd></div></dl></section><section><label>Detected stack</label><div className={styles.stack}>{stack.length?stack.map(item=><span key={item}>{item}</span>):<p>No stack metadata detected.</p>}</div></section><section><label>Repository</label><p>Git state is unavailable until the project Git service is connected.</p></section><section><label>Runtime policy</label><p>Agents inherit global tool policies. Project and agent overrides remain a future resolution layer.</p></section></div>; }

function Agents({projectId}:{projectId:string}) {
  const [agents,setAgents]=useState<Agent[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState<string|null>(null); const [saved,setSaved]=useState<string|null>(null);
  useEffect(()=>{let alive=true; void Promise.all([fetch(`${serverUrl}/api/projects/${projectId}/agents`),fetch(`${serverUrl}/api/provider-accounts`)]).then(async([a,p])=>{if(!a.ok||!p.ok)throw new Error("Unable to load project agents."); if(alive){setAgents((await a.json() as Agent[]).map(item=>({...item})));setAccounts(await p.json() as Account[]);}}).catch(reason=>alive&&setError(reason instanceof Error?reason.message:"Unable to load project agents."));return()=>{alive=false};},[projectId]);
  const change=(id:string,patch:Partial<Agent>)=>setAgents(current=>current.map(agent=>agent.id===id?{...agent,...patch}:agent));
  const save=async(agent:Agent)=>{setSaving(agent.id);setSaved(null);setError(null);try{const response=await fetch(`${serverUrl}/api/projects/${projectId}/agents/${agent.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:agent.name,instructions:agent.instructions,browserProfileId:agent.browserProfileId||null,model:agent.model||null,enabled:agent.enabled})});const body=await response.json().catch(()=>null) as Agent|{error?:string}|null;if(!response.ok)throw new Error((body as {error?:string}|null)?.error??"Unable to save agent.");setAgents(current=>current.map(item=>item.id===agent.id?{...(body as Agent)}:item));setSaved(agent.id);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save agent.");}finally{setSaving(null)}};
  if(error&&!agents.length)return <div className={styles.agentError}><CircleAlert/> {error}</div>;
  return <section className={styles.agentManagement}><header><div><span>Project team</span><h2>Agent identities</h2><p>Lead owns user-facing project conversations. Coder is ready for future delegated runs; no delegation occurs yet.</p></div><aside><strong>{agents.filter(a=>a.enabled).length}</strong><span>enabled</span></aside></header>{error?<div className={styles.agentError}><CircleAlert/> {error}</div>:null}<div className={styles.agentRows}>{agents.map(agent=><article key={agent.id} className={styles.agentRow}><header><span className={styles.agentGlyph}>{agent.isLead?<Crown/>:<Bot/>}</span><div><strong>{agent.name}</strong><small>{agent.isLead?"Lead agent":agent.role}</small></div><label className={styles.agentToggle}><input type="checkbox" checked={agent.enabled} onChange={event=>change(agent.id,{enabled:event.target.checked})}/><span>{agent.enabled?"Enabled":"Disabled"}</span></label></header><div className={styles.agentFields}><label>Name<input value={agent.name} onChange={event=>change(agent.id,{name:event.target.value})}/></label><label>Provider account<select value={agent.browserProfileId??""} onChange={event=>change(agent.id,{browserProfileId:event.target.value||null})}><option value="">Not assigned</option>{accounts.map(account=><option key={account.id} value={account.id} disabled={!account.connected}>{account.name} · {account.providerType}{account.connected?"":" (disconnected)"}</option>)}</select></label><label>Model<input value={agent.model??""} placeholder="Provider default" onChange={event=>change(agent.id,{model:event.target.value||null})}/></label><label className={styles.agentInstructions}>Instructions<textarea value={agent.instructions} placeholder={agent.isLead?"How should this agent plan, communicate, and delegate?":"What coding work should this agent specialize in?"} onChange={event=>change(agent.id,{instructions:event.target.value})}/></label></div><footer><span>Permissions: global defaults</span><button disabled={saving===agent.id} onClick={()=>void save(agent)}>{saved===agent.id?<Check/>:<Save/>}{saving===agent.id?"Saving…":saved===agent.id?"Saved":"Save agent"}</button></footer></article>)}</div></section>;
}

function detectStack(nodes:ProjectTreeNode[]){const names=new Set<string>();const visit=(items:ProjectTreeNode[])=>items.forEach(item=>{names.add(item.name.toLowerCase());if(item.children)visit(item.children)});visit(nodes);const stack:string[]=[];if(names.has("package.json"))stack.push("Node.js");if([...names].some(name=>name.endsWith(".tsx")))stack.push("React");if(names.has("tsconfig.json"))stack.push("TypeScript");if([...names].some(name=>name.endsWith(".csproj")))stack.push(".NET");return stack;}
