import Editor, { type OnValidate } from "@monaco-editor/react";
import { Code2, Save, X } from "lucide-react";
import type { EditorDocument } from "../domain";
import { configureDCodeMonaco, editorLanguage, modelPath } from "./monaco-themes";

export function EditorStage({ documents, active, activePath, theme, saving, onSelect, onClose, onChange, onSave, onErrors }: { documents: EditorDocument[]; active: EditorDocument | null; activePath: string | null; theme: string; saving: boolean; onSelect(path: string): void; onClose(path: string): void; onChange(path: string, content: string): void; onSave(document: EditorDocument): void; onErrors(path: string, count: number): void }) {
  return <main className="pe-stage">
    <header className="pe-stage__chrome"><div className="pe-stage__tabs">{documents.map((document) => <div key={document.relativePath} className={`pe-file-tab ${document.relativePath === activePath ? "is-active" : ""}`}><button onClick={() => onSelect(document.relativePath)}><Code2 size={13} /><span>{document.name}</span>{document.content !== document.savedContent ? <i /> : null}</button><button aria-label={`Close ${document.name}`} onClick={() => onClose(document.relativePath)}><X size={12} /></button></div>)}</div>{active ? <button className="pe-stage__save" disabled={active.loading || active.content === active.savedContent || saving} onClick={() => onSave(active)}><Save size={13} />{saving ? "Saving" : "Save"}</button> : null}</header>
    {active ? <><div className="pe-stage__context">{active.relativePath.split(/[\\/]/).map((part, index) => <span key={`${part}-${index}`}>{part}</span>)}</div>{active.error ? <div className="pe-stage__error">{active.error}</div> : null}<div className="pe-stage__editor">{active.loading ? <div className="pe-stage__loading">Opening {active.name}…</div> : <Editor path={modelPath(active.relativePath)} language={editorLanguage(active.name)} value={active.content} theme={theme} beforeMount={configureDCodeMonaco} onChange={(value) => onChange(active.relativePath, value ?? "")} onValidate={(markers: Parameters<OnValidate>[0]) => onErrors(active.relativePath, markers.filter((marker) => marker.severity === 8).length)} options={{ automaticLayout: true, fontSize: 13, fontFamily: "var(--font-mono, 'Cascadia Code', Consolas, monospace)", lineHeight: 21, minimap: { enabled: true, scale: 1, showSlider: "mouseover" }, padding: { top: 16, bottom: 16 }, renderLineHighlight: "all", bracketPairColorization: { enabled: true }, guides: { bracketPairs: false, indentation: true, highlightActiveIndentation: true }, overviewRulerBorder: false, glyphMargin: false, foldingHighlight: false, scrollbar: { verticalScrollbarSize: 7, horizontalScrollbarSize: 7, useShadows: false }, scrollBeyondLastLine: false, smoothScrolling: true }} />}</div></> : <div className="pe-stage__empty"><div className="pe-stage__monogram">&gt;_</div><strong>Ready to build.</strong><p>Open a file from Project. DCode restores your working set automatically.</p></div>}
  </main>;
}
