"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowDown, Code2, Crown, ExternalLink, MessageSquarePlus, MoreHorizontal, Pencil, Send, ShieldAlert, Square, Trash2, UserRound } from "lucide-react";
import { MarkdownMessage } from "../../project/chat/markdown-message";
import type { BrowserProfile, ChatConversation, ChatMessage, ConversationProgress, PendingToolApproval, ProjectChatExecutionTurn, ProjectChatStreamEvent, ProjectConversationCollection } from "../../project/chat/project-chat-types";
import { ExecutionTranscript } from "./execution-transcript";
import styles from "../project-environment.module.css";

const serverUrl = "http://localhost:5283";
type ProjectAgent={id:string;name:string;role:string;enabled:boolean;isLead:boolean;browserProfileId:string|null;accountName:string|null;model:string|null};
type AgentSession={id:string;agentId:string;conversationId:string;status:string;remoteConversationReference:string|null};

export function ProjectConversation({ projectId }: { projectId: string }) {
  const [profiles, setProfiles] = useState<BrowserProfile[]>([]); const [conversations, setConversations] = useState<ChatConversation[]>([]); const [chat, setChat] = useState<ChatConversation | null>(null); const [profileId, setProfileId] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [turns, setTurns] = useState<ProjectChatExecutionTurn[]>([]); const [live, setLive] = useState<ConversationProgress[]>([]); const [activeUserId, setActiveUserId] = useState<string | null>(null);
  const [draft, setDraft] = useState(""); const [sending, setSending] = useState(false); const [error, setError] = useState<string | null>(null); const [approvals, setApprovals] = useState<PendingToolApproval[]>([]); const [approvalAction, setApprovalAction] = useState<string | null>(null); const [showJump, setShowJump] = useState(false); const [warmProfile, setWarmProfile] = useState<{ id: string; status: "preparing" | "ready" | "error"; error?: string } | null>(null); const [warmRetry, setWarmRetry] = useState(0);
  const [editingTitle,setEditingTitle]=useState(false);const [titleDraft,setTitleDraft]=useState("");const [conversationAction,setConversationAction]=useState(false);
  const [agents,setAgents]=useState<ProjectAgent[]>([]);const [agentSessions,setAgentSessions]=useState<AgentSession[]>([]);
  const timelineRef = useRef<HTMLDivElement | null>(null); const timelineContentRef = useRef<HTMLDivElement | null>(null); const endRef = useRef<HTMLDivElement | null>(null); const autoFollowRef = useRef(true); const pointerScrollingRef = useRef(false); const abortRef = useRef<AbortController | null>(null);
  const delegationRecoveryRef=useRef(new Set<string>());

  // Conversation restoration is intentionally keyed only by project changes; restore is a local request helper.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { let alive = true; void Promise.all([fetch(`${serverUrl}/api/providers/browser/deepseek/profiles`), fetch(`${serverUrl}/api/projects/${projectId}/chats`)]).then(async ([profileResponse, chatsResponse]) => { if (!profileResponse.ok || !chatsResponse.ok) throw new Error("Unable to load project conversations."); const connected = (await profileResponse.json() as BrowserProfile[]).filter((profile) => profile.connected); const collection = await chatsResponse.json() as ProjectConversationCollection; const restored = collection.conversations.find((item) => item.id === collection.activeConversationId) ?? collection.conversations[0] ?? null; if (!alive) return; setProfiles(connected); setConversations(collection.conversations.map((item) => ({ ...item }))); setChat(restored); setProfileId(restored?.browserProfileId ?? connected[0]?.id ?? ""); if (restored) await restore(restored.id, alive); }).catch((reason: unknown) => { if (alive) setError(reason instanceof Error ? reason.message : "Unable to load conversations."); }); return () => { alive = false; }; }, [projectId]);
  useEffect(()=>{let alive=true;void Promise.all([fetch(`${serverUrl}/api/projects/${projectId}/agents`),fetch(`${serverUrl}/api/projects/${projectId}/agent-sessions`)]).then(async([a,s])=>{if(!a.ok||!s.ok)throw new Error("Unable to load the project Agent team.");if(alive){setAgents(await a.json() as ProjectAgent[]);setAgentSessions(await s.json() as AgentSession[]);}}).catch(reason=>{if(alive)setError(reason instanceof Error?reason.message:"Unable to load the Agent team.")});return()=>{alive=false};},[projectId,sending]);
  useEffect(() => {
    let active = true;
    const preparationFrame = window.requestAnimationFrame(() => {
      if (active) setWarmProfile(profileId ? { id: profileId, status: "preparing" } : null);
    });
    if (!profileId) return () => { active = false; window.cancelAnimationFrame(preparationFrame); };
    const leaseId = `project:${projectId}`;
    const controller = new AbortController();
    const timeout = window.setTimeout(() => controller.abort(), 80_000);
    void fetch(`${serverUrl}/api/providers/browser/deepseek/profiles/${profileId}/warm`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leaseId }), signal: controller.signal })
      .then(async (response) => {
        if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string } | null; throw new Error(body?.error ?? "Unable to prepare provider session."); }
        if (active) setWarmProfile({ id: profileId, status: "ready" });
      })
      .catch((reason: unknown) => {
        if (active) setWarmProfile({ id: profileId, status: "error", error: reason instanceof DOMException && reason.name === "AbortError" ? "Provider startup timed out." : reason instanceof Error ? reason.message : "Unable to prepare provider session." });
      })
      .finally(() => window.clearTimeout(timeout));
    return () => {
      active = false; controller.abort(); window.cancelAnimationFrame(preparationFrame); window.clearTimeout(timeout);
      void fetch(`${serverUrl}/api/providers/browser/deepseek/profiles/${profileId}/warm/release`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leaseId }), keepalive: true });
    };
  }, [profileId, projectId, warmRetry]);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { if (autoFollowRef.current) scrollToLatest(); else setShowJump(true); }); return () => window.cancelAnimationFrame(frame); }, [live, messages, approvals, sending]);
  useEffect(() => { const timeline = timelineRef.current; const content = timelineContentRef.current; if (!timeline || !content || typeof ResizeObserver === "undefined") return; const observer = new ResizeObserver(() => { if (autoFollowRef.current) timeline.scrollTop = timeline.scrollHeight; }); observer.observe(content); return () => observer.disconnect(); }, []);

  async function restore(chatId: string, alive = true) { const [messagesResponse, turnsResponse, approvalsResponse] = await Promise.all([fetch(`${serverUrl}/api/chats/${chatId}/messages`), fetch(`${serverUrl}/api/chats/${chatId}/execution-turns`), fetch(`${serverUrl}/api/projects/${projectId}/tool-approvals`)]); if (alive && messagesResponse.ok) setMessages((await messagesResponse.json() as ChatMessage[]).map((message) => ({ ...message }))); const restoredTurns=turnsResponse.ok?(await turnsResponse.json() as ProjectChatExecutionTurn[]).map((turn) => ({ ...turn, events: turn.events.map((event) => ({ ...event })) })):[]; const restoredApprovals=approvalsResponse.ok?(await approvalsResponse.json() as PendingToolApproval[]).map((approval) => ({ ...approval, arguments: { ...approval.arguments } })):[]; if(alive){if(turnsResponse.ok)setTurns(restoredTurns);if(approvalsResponse.ok)setApprovals(restoredApprovals);const waiting=restoredTurns.find(turn=>turn.status==="waiting_delegation");if(waiting&&!hasPendingChildApproval(waiting,restoredApprovals)&&!delegationRecoveryRef.current.has(waiting.id)){delegationRecoveryRef.current.add(waiting.id);void resumeWaitingDelegation(waiting.id,chatId);}} }

  async function resumeWaitingDelegation(runId:string,chatId:string){setSending(true);setError(null);try{const response=await fetch(`${serverUrl}/api/agent-runs/${runId}/resume-delegation`,{method:"POST"});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string}|null;throw new Error(body?.error??"Unable to resume the Lead Agent.");}if(!response.body)throw new Error("The Lead continuation stream was empty.");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const chunk=await reader.read();buffer+=decoder.decode(chunk.value,{stream:!chunk.done});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line) as ProjectChatStreamEvent;if(event.type==="progress"&&event.progress)applyProgress(event.progress);else if(event.type==="result"&&event.result?.exchange?.conversation.id===chatId){updateConversation(event.result.exchange.conversation);setMessages(event.result.exchange.messages.map(message=>({...message})));}}if(chunk.done)break;}await restore(chatId,true);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to resume the Lead Agent.");}finally{setSending(false);}}
  async function ensureChat() { if (chat) return chat; if (!profileId) throw new Error("Connect a provider account before starting a conversation."); const response = await fetch(`${serverUrl}/api/projects/${projectId}/chats`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ browserProfileId: profileId }) }); if (!response.ok) throw new Error("Unable to create the project conversation."); const created = await response.json() as ChatConversation; setChat(created); setConversations((current) => [created, ...current.filter((item) => item.id !== created.id)]); return created; }
  function updateConversation(conversation: ChatConversation) { const next = { ...conversation }; setChat(next); setConversations((current) => [next, ...current.filter((item) => item.id !== next.id)]); }
  function applyProgress(progress: ConversationProgress) { const next = { ...progress }; setLive((current) => current.some((item) => item.id === next.id) ? current.map((item) => item.id === next.id ? next : item) : [...current, next]); }

  async function send() {
    const content = draft.trim(); const providerReady = warmProfile?.id === profileId && warmProfile.status === "ready"; if (!content || sending || !providerReady) return; const optimisticId = `pending-${Date.now()}`;
    setDraft(""); setError(null); setLive([]); setActiveUserId(optimisticId); setSending(true); autoFollowRef.current = true; setShowJump(false); setMessages((current) => [...current, { id: optimisticId, role: "user", content }]);
    try { const activeChat = await ensureChat(); const controller = new AbortController(); abortRef.current = controller; const response = await fetch(`${serverUrl}/api/projects/${projectId}/chat/messages/stream`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chatId: activeChat.id, content }), signal: controller.signal }); if (!response.ok) { const failure = await response.json().catch(() => null) as { error?: string } | null; throw new Error(failure?.error ?? `Conversation failed (HTTP ${response.status}).`); } if (!response.body) throw new Error("The conversation stream was empty."); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let resultReceived = false;
      while (true) { const chunk = await reader.read(); buffer += decoder.decode(chunk.value, { stream: !chunk.done }); const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) { if (!line.trim()) continue; const event = JSON.parse(line) as ProjectChatStreamEvent; if (event.type === "exchange" && event.exchange) { updateConversation(event.exchange.conversation); setMessages(event.exchange.messages.map((message) => ({ ...message }))); setActiveUserId([...event.exchange.messages].reverse().find((message) => message.role === "user")?.id ?? null); } else if (event.type === "progress" && event.progress) applyProgress(event.progress); else if (event.type === "result" && event.result) { resultReceived = true; if (event.result.exchange) { updateConversation(event.result.exchange.conversation); setMessages(event.result.exchange.messages.map((message) => ({ ...message }))); } await restore(activeChat.id); if (!['completed','waiting_permission','waiting_delegation'].includes(event.result.status)) setError(event.result.error ?? "The agent could not complete this turn."); } } if (chunk.done) break; }
      if (!resultReceived) throw new Error("The conversation ended before a final response arrived.");
    } catch (reason) { const cancelled = reason instanceof DOMException && reason.name === "AbortError"; setLive((current) => current.map((item) => item.status === "running" ? { ...item, status: cancelled ? "cancelled" : "failed" } : item)); setError(cancelled ? "Run stopped. Completed work was preserved." : reason instanceof Error ? reason.message : "Unable to send message."); } finally { abortRef.current = null; setSending(false); }
  }

  async function resolveApproval(pending: PendingToolApproval, action: "once" | "always" | "deny") {
    if (pending.status !== "pending" || approvalAction) return; const actionKey = `${pending.toolCallId}:${action}`; setApprovalAction(actionKey); setError(null);
    try { const delegatedApproval = pending.chatId !== chat?.id; const endpoint = `${serverUrl}/api/project-chat/runs/${pending.runId}/tool-calls/${pending.toolCallId}/${action === "deny" ? "deny" : "approve"}`; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: action === "deny" ? undefined : JSON.stringify({ alwaysAllow: action === "always" }) }); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string } | null; throw new Error(body?.error ?? `Approval failed (HTTP ${response.status}).`); } setApprovals((current) => current.map((approval) => approval.runId === pending.runId && approval.toolCallId === pending.toolCallId ? { ...approval, status: action === "deny" ? "denied" : action === "always" ? "always_allowed" : "approved" } : approval));
      if (action === "deny") { const body = await response.json() as { progress: ConversationProgress }; if (!delegatedApproval) applyProgress(body.progress); if (chat) await restore(chat.id); return; } if (!response.body) throw new Error("The approval continuation stream was empty."); setSending(true); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = "";
      while (true) { const chunk = await reader.read(); buffer += decoder.decode(chunk.value, { stream: !chunk.done }); const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) { if (!line.trim()) continue; const event = JSON.parse(line) as ProjectChatStreamEvent; if (event.type === "progress" && event.progress && (!delegatedApproval || !event.progress.id.startsWith(pending.runId))) applyProgress(event.progress); else if (event.type === "result" && event.result) { const visibleExchange=event.result.exchange?.conversation.id===chat?.id; if (event.result.exchange && (!delegatedApproval || visibleExchange)) { updateConversation(event.result.exchange.conversation); setMessages(event.result.exchange.messages.map((message) => ({ ...message }))); } if (event.result.status !== "completed" && event.result.status !== "waiting_permission") setError(event.result.error ?? "The approved run could not complete."); } } if (chunk.done) break; } if (chat) await restore(chat.id);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to resolve approval."); if (chat) await restore(chat.id); } finally { setApprovalAction(null); setSending(false); }
  }

  function onTimelineScroll() { const element = timelineRef.current; if (!element) return; const near = element.scrollHeight - element.scrollTop - element.clientHeight < 72; if (near) { autoFollowRef.current = true; setShowJump(false); } else if (pointerScrollingRef.current) { autoFollowRef.current = false; setShowJump(true); } }
  function pauseAutoFollow() { autoFollowRef.current = false; setShowJump(true); }
  function scrollToLatest(behavior: ScrollBehavior = "auto") { const element = timelineRef.current; if (!element) return; element.scrollTo({ top: element.scrollHeight, behavior }); }
  function jumpToLatest() { autoFollowRef.current = true; setShowJump(false); scrollToLatest("smooth"); }
  async function switchConversation(chatId: string) { if (sending || chatId === chat?.id) return; const selected = conversations.find((item) => item.id === chatId); if (!selected) return; setError(null); setLive([]); setMessages([]); setTurns([]); setApprovals([]); setActiveUserId(null); const response = await fetch(`${serverUrl}/api/projects/${projectId}/chats/${chatId}/active`, { method: "PUT" }); if (!response.ok) { setError("Unable to open that conversation."); return; } setChat({ ...selected }); setProfileId(selected.browserProfileId); autoFollowRef.current = true; await restore(chatId); }
  function newConversation() { if (sending) return; setChat(null); setMessages([]); setTurns([]); setLive([]); setActiveUserId(null); setApprovals([]); setError(null); }
  async function renameConversation(){if(!chat||conversationAction)return;const title=titleDraft.trim();if(!title)return;setConversationAction(true);setError(null);try{const response=await fetch(`${serverUrl}/api/projects/${projectId}/chats/${chat.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title})});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string;detail?:string}|null;throw new Error(body?.error??body?.detail??"Unable to rename the conversation.");}updateConversation(await response.json() as ChatConversation);setEditingTitle(false);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to rename the conversation.");}finally{setConversationAction(false);}}
  async function deleteConversation(){if(!chat||conversationAction||!window.confirm(`Delete '${chat.title}' from DCode? The DeepSeek conversation will remain in your provider account.`))return;const deletedId=chat.id;setConversationAction(true);setError(null);try{const response=await fetch(`${serverUrl}/api/projects/${projectId}/chats/${deletedId}`,{method:"DELETE"});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string}|null;throw new Error(body?.error??"Unable to delete the conversation.");}const remaining=conversations.filter(item=>item.id!==deletedId);setConversations(remaining);setChat(null);setMessages([]);setTurns([]);setLive([]);setApprovals([]);setActiveUserId(null);if(remaining[0])await switchConversation(remaining[0].id);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to delete the conversation.");}finally{setConversationAction(false);}}
  async function openProviderConversation(){if(!chat||conversationAction)return;setConversationAction(true);setError(null);try{const response=await fetch(`${serverUrl}/api/projects/${projectId}/chats/${chat.id}/open`,{method:"POST"});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string;detail?:string}|null;throw new Error(body?.error??body?.detail??"Unable to open the provider conversation.");}}catch(reason){setError(reason instanceof Error?reason.message:"Unable to open the provider conversation.");}finally{setConversationAction(false);}}

  const lead=agents.find(agent=>agent.isLead);const coder=agents.find(agent=>agent.role==="coder");const coderSession=coder?agentSessions.find(session=>session.agentId===coder.id):null;
  return <section className={styles.conversation}>
    <header className={styles.conversationHeader}><div className={styles.leadIdentity}><span className={`${styles.agentAvatar} ${styles.leadAvatar}`}><Crown/></span><div><span>Lead · {warmProfile?.status === "ready" ? "Ready" : warmProfile?.status === "error" ? "Unavailable" : "Starting"}</span><strong>{lead?.name??"Lead"}</strong></div><i title={warmProfile?.error} className={`${styles.presence} ${warmProfile?.id===profileId&&warmProfile.status==="ready"?styles.presenceReady:warmProfile?.status==="error"?styles.presenceError:styles.presencePreparing}`}/>{warmProfile?.status === "error" ? <button className={styles.warmRetry} title={warmProfile.error} onClick={() => setWarmRetry(value => value + 1)}>Retry</button> : null}</div><div className={styles.conversationChooser}><span>Conversation</span>{editingTitle?<input autoFocus value={titleDraft} maxLength={80} disabled={conversationAction} onChange={event=>setTitleDraft(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")void renameConversation();if(event.key==="Escape")setEditingTitle(false);}}/>:<select aria-label="Project conversation" value={chat?.id??""} disabled={sending} onChange={event=>void switchConversation(event.target.value)}><option value="">New Lead conversation</option>{conversations.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select>}</div><div className={styles.conversationActions}><button onClick={newConversation} disabled={sending} title="New Lead conversation"><MessageSquarePlus size={16}/></button>{chat?<details className={styles.conversationMenu}><summary title="Conversation actions"><MoreHorizontal size={16}/></summary><div><button onClick={()=>{setTitleDraft(chat.title);setEditingTitle(true)}}><Pencil/>Rename</button>{chat.providerConversationUrl?<button disabled={conversationAction} onClick={()=>void openProviderConversation()}><ExternalLink/>Open in DeepSeek</button>:null}<details><summary>Technical details</summary><dl><div><dt>Provider</dt><dd>{chat.providerType} · {chat.transport}</dd></div><div><dt>Account</dt><dd>{chat.accountName}</dd></div><div><dt>Remote chat</dt><dd>{chat.providerConversationId??"Not created"}</dd></div></dl></details><button className={styles.dangerAction} onClick={()=>void deleteConversation()}><Trash2/>Delete</button></div></details>:null}</div></header>
    <div className={styles.agentTeamBar}><span>Project team</span><div><span className={styles.teamMember}><Crown/><strong>{lead?.name??"Lead"}</strong><small>{lead?.enabled===false?"Disabled":"Conversation owner"}</small></span><span className={styles.teamFlow}>→</span><span className={styles.teamMember}><Code2/><strong>{coder?.name??"Coder"}</strong><small>{!coder?.browserProfileId?"Provider not assigned":coderSession?"Session ready":"Starts on delegation"}</small></span></div></div>
    {!chat ? <label className={styles.accountPicker}><span>Provider account</span><select value={profileId} onChange={(event) => setProfileId(event.target.value)}><option value="">No connected accounts</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>DeepSeek · {profile.name}</option>)}</select></label> : null}
    <div ref={timelineRef} className={styles.timeline} tabIndex={0} onScroll={onTimelineScroll} onWheel={(event) => { if (event.deltaY < 0) pauseAutoFollow(); }} onPointerDown={() => { pointerScrollingRef.current = true; }} onPointerUp={() => { pointerScrollingRef.current = false; }} onPointerCancel={() => { pointerScrollingRef.current = false; }} onKeyDown={(event) => { if (["ArrowUp", "PageUp", "Home"].includes(event.key)) pauseAutoFollow(); }}><div ref={timelineContentRef} className={styles.timelineContent}>{messages.length === 0 ? <ConversationEmpty connected={profiles.length > 0} leadName={lead?.name??"Lead"}/> : messages.map((message) => { const restored = turns.find((turn) => turn.userMessageId === message.id); const events = activeUserId === message.id && live.length ? live : restored?.events ?? []; return <div className={styles.turn} key={message.id}><ConversationMessage message={message} leadName={lead?.name??"Lead"}/>{message.role === "user" && events.length ? <ExecutionTranscript events={events} approvals={approvals} busyApproval={approvalAction} leadName={lead?.name??"Lead"} coderName={coder?.name??"Coder"} onApproval={(approval, action) => void resolveApproval(approval, action)} /> : null}</div>; })}{sending && !live.length ? <div className={styles.thinking}><span /><span>{lead?.name??"Lead"} is thinking…</span></div> : null}{error ? <div className={styles.conversationError}><ShieldAlert size={15} /><span>{error}</span></div> : null}<div ref={endRef} /></div></div>
    {showJump ? <button className={styles.jumpLatest} onClick={jumpToLatest}><ArrowDown size={14} />Latest</button> : null}
    <footer className={styles.composer}><div className={styles.composerSurface}><textarea rows={2} value={draft} disabled={sending || !profiles.length || warmProfile?.status !== "ready"} aria-label="Message DCode Agent" placeholder={!profiles.length ? "Connect a provider account in Providers" : warmProfile?.status === "error" ? "Provider unavailable — retry the Lead session" : warmProfile?.status !== "ready" ? "Preparing the Lead session…" : "Ask DCode to inspect, explain, or change this project…"} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} /><div className={styles.composerBar}><span>{warmProfile?.status === "ready" ? "Project context" : warmProfile?.status === "error" ? warmProfile.error : "Starting provider session"}</span><div><small><kbd>Enter</kbd> send</small>{sending ? <button className={styles.stop} onClick={() => abortRef.current?.abort()}><Square size={12} />Stop</button> : <button className={styles.send} disabled={!draft.trim() || !profiles.length || warmProfile?.status !== "ready"} onClick={() => void send()}><Send size={14} /><span>Send</span></button>}</div></div></div></footer>
  </section>;
}

function ConversationMessage({ message,leadName }: { message: ChatMessage;leadName:string }) { const assistant = message.role === "assistant"; return <article className={`${styles.message} ${assistant ? `${styles.assistant} ${styles.finalResponse}` : styles.user}`}><div className={styles.messageMeta}>{assistant ? <Crown size={15} /> : <UserRound size={15} />}<strong>{assistant ? leadName : "You"}</strong>{assistant ? <span>Completed</span> : null}</div><div className={styles.messageBody}>{assistant ? <MarkdownMessage content={message.content} /> : <p>{message.content}</p>}</div></article>; }
function ConversationEmpty({ connected,leadName }: { connected: boolean;leadName:string }) { return <div className={styles.conversationEmpty}><div>&gt;_</div><strong>{connected ? `Plan with ${leadName}` : "Connect a provider"}</strong><p>{connected ? "The Lead owns this conversation, can work directly, and may delegate bounded implementation work to Coder. Both Agents appear in one execution transcript." : "A connected provider account is required for project chat."}</p></div>; }
function hasPendingChildApproval(turn:ProjectChatExecutionTurn,approvals:PendingToolApproval[]){const waiting=turn.events.findLast(event=>event.stage==="delegation_waiting");if(!waiting?.detail)return false;try{const detail=JSON.parse(waiting.detail) as {ChildRunId?:string;childRunId?:string};const childId=detail.ChildRunId??detail.childRunId;return Boolean(childId&&approvals.some(approval=>approval.runId===childId&&approval.status==="pending"));}catch{return false;}}
