"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, Play, RotateCw, Settings2, Square } from "lucide-react";
import styles from "../project-environment.module.css";

const serverUrl = "http://localhost:5283";
type Configuration = { id:string; name:string; command:string; arguments:string[]; workingDirectory:string };
type Execution = { id:string; configurationId:string; status:string };

export function ProjectRunControl({projectId,onOpenRuntime}:{projectId:string;onOpenRuntime():void}) {
  const [configurations,setConfigurations]=useState<Configuration[]>([]);const [executions,setExecutions]=useState<Execution[]>([]);const [selected,setSelected]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const storageKey=`dcode:project:${projectId}:default-run`;
  const refresh=useCallback(async()=>{const[c,e]=await Promise.all([fetch(`${serverUrl}/api/projects/${projectId}/run-configurations`),fetch(`${serverUrl}/api/projects/${projectId}/run-executions`)]);if(!c.ok||!e.ok)throw new Error("Unable to load run configurations.");const next=await c.json() as Configuration[];setConfigurations(next);setExecutions(await e.json() as Execution[]);setSelected(current=>{const preferred=current||window.localStorage.getItem(storageKey)||"";return next.some(item=>item.id===preferred)?preferred:next[0]?.id??"";});},[projectId,storageKey]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh().catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load runs.")),0);return()=>window.clearTimeout(timer);},[refresh]);
  const active=executions.find(item=>item.status==="running"||item.status==="stopping");
  useEffect(()=>{if(!active)return;const timer=window.setInterval(()=>void refresh(),700);return()=>window.clearInterval(timer);},[active,refresh]);
  const configuration=useMemo(()=>configurations.find(item=>item.id===selected),[configurations,selected]);
  function choose(id:string){setSelected(id);window.localStorage.setItem(storageKey,id);}
  async function start(id=selected){if(!id||busy)return;setBusy(true);setError(null);onOpenRuntime();try{const response=await fetch(`${serverUrl}/api/projects/${projectId}/run-configurations/${id}/start`,{method:"POST"});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string}|null;throw new Error(body?.error??"Unable to start the run.");}choose(id);await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to start the run.");}finally{setBusy(false);}}
  async function stop(){if(!active||busy)return;setBusy(true);setError(null);onOpenRuntime();try{const response=await fetch(`${serverUrl}/api/projects/${projectId}/run-executions/${active.id}/stop`,{method:"POST"});if(!response.ok)throw new Error("Unable to stop the run.");await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to stop the run.");}finally{setBusy(false);}}
  async function restart(){if(!active||busy)return;const id=active.configurationId;setBusy(true);setError(null);onOpenRuntime();try{await fetch(`${serverUrl}/api/projects/${projectId}/run-executions/${active.id}/stop`,{method:"POST"});for(let attempt=0;attempt<30;attempt++){await new Promise(resolve=>window.setTimeout(resolve,200));const response=await fetch(`${serverUrl}/api/projects/${projectId}/run-executions`);const current=await response.json() as Execution[];if(!current.some(item=>item.id===active.id&&(item.status==="running"||item.status==="stopping")))break;}const response=await fetch(`${serverUrl}/api/projects/${projectId}/run-configurations/${id}/start`,{method:"POST"});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string}|null;throw new Error(body?.error??"Unable to restart the run.");}choose(id);await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to restart the run.");}finally{setBusy(false);}}
  return <div className={styles.projectRunControl} title={error??undefined}><button className={styles.runMain} disabled={busy||(!selected&&!active)} onClick={()=>active?void stop():void start()}>{active?<><Square/>Stop</>:<><Play/>Run{configuration?<span>{configuration.name}</span>:null}</>}</button>{active?<button className={styles.restartRun} disabled={busy} onClick={()=>void restart()} title="Restart current run"><RotateCw/></button>:null}<details><summary aria-label="Choose run configuration"><ChevronDown/></summary><div className={styles.runMenu}><header><strong>Run configuration</strong><span>{error??(active?"A project process is running.":"Choose the project command to run.")}</span></header>{configurations.map(item=><button key={item.id} onClick={()=>{choose(item.id);if(!active)void start(item.id)}}><span><strong>{item.name}</strong><small>{item.command} {item.arguments.join(" ")}</small></span>{item.id===selected?<Check/>:null}</button>)}<button onClick={onOpenRuntime}><Settings2/><span><strong>Manage configurations</strong><small>Create, edit, or remove project commands</small></span></button></div></details></div>;
}
