"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { Play,Plus,Square,Trash2,X } from "lucide-react";
import styles from "../project-environment.module.css";

const serverUrl="http://localhost:5283";
type Configuration={id:string;name:string;command:string;arguments:string[];workingDirectory:string;isDetected:boolean};
type Execution={id:string;configurationId:string;status:string;command:string;arguments:string[];workingDirectory:string;stdout:string;stderr:string;exitCode:number|null;error:string|null;createdUtc:string};

export function RunConfigurations({projectId}:{projectId:string}){
 const[configurations,setConfigurations]=useState<Configuration[]>([]),[executions,setExecutions]=useState<Execution[]>([]),[selected,setSelected]=useState(""),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const refresh=useCallback(async()=>{const[c,e]=await Promise.all([fetch(`${serverUrl}/api/projects/${projectId}/run-configurations`),fetch(`${serverUrl}/api/projects/${projectId}/run-executions`)]);if(!c.ok||!e.ok)throw new Error("Unable to load project run configurations.");const nextConfigurations=await c.json() as Configuration[],nextExecutions=await e.json() as Execution[];setConfigurations(nextConfigurations);setExecutions(nextExecutions);setSelected(current=>current&&nextConfigurations.some(item=>item.id===current)?current:nextConfigurations[0]?.id??"");},[projectId]);
 useEffect(()=>{let alive=true;const timer=window.setTimeout(()=>void refresh().catch(reason=>{if(alive)setError(reason instanceof Error?reason.message:"Unable to load runs.")}),0);return()=>{alive=false;window.clearTimeout(timer);};},[refresh]);
 useEffect(()=>{if(!executions.some(item=>item.status==="running"||item.status==="stopping"))return;const timer=window.setInterval(()=>void refresh(),700);return()=>window.clearInterval(timer);},[executions,refresh]);
 const active=executions.find(item=>item.status==="running"||item.status==="stopping"),latest=active??executions.find(item=>item.configurationId===selected)??executions[0],configuration=configurations.find(item=>item.id===selected);
 async function start(){if(!selected||busy)return;setBusy(true);setError(null);try{const response=await fetch(`${serverUrl}/api/projects/${projectId}/run-configurations/${selected}/start`,{method:"POST"});if(!response.ok)throw new Error((await response.json().catch(()=>null) as {error?:string}|null)?.error??"Unable to start command.");await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to start command.");}finally{setBusy(false);}}
 async function stop(){if(!active||busy)return;setBusy(true);try{await fetch(`${serverUrl}/api/projects/${projectId}/run-executions/${active.id}/stop`,{method:"POST"});await refresh();}finally{setBusy(false);}}
 async function remove(){if(!configuration||busy||!window.confirm(`Delete run configuration '${configuration.name}'?`))return;setBusy(true);try{const response=await fetch(`${serverUrl}/api/projects/${projectId}/run-configurations/${configuration.id}`,{method:"DELETE"});if(!response.ok)throw new Error((await response.json().catch(()=>null) as {error?:string}|null)?.error??"Unable to delete configuration.");await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to delete configuration.");}finally{setBusy(false);}}
 return <div className={styles.runSurface}><div className={styles.runToolbar}><select aria-label="Run configuration" value={selected} onChange={event=>setSelected(event.target.value)}>{configurations.length?configurations.map(item=><option key={item.id} value={item.id}>{item.name}</option>):<option value="">No configurations</option>}</select><button className={styles.runPrimary} disabled={!selected||Boolean(active)||busy} onClick={()=>void start()}><Play/>Run</button>{active?<button onClick={()=>void stop()}><Square/>Stop</button>:null}<button onClick={()=>setShowForm(true)}><Plus/>New</button>{configuration&&!configuration.isDetected?<button title="Delete configuration" onClick={()=>void remove()}><Trash2/></button>:null}<span>{configuration?<><code>{configuration.command} {configuration.arguments.join(" ")}</code><small>{configuration.workingDirectory}</small></>:"Add a command or package.json script."}</span></div>{showForm?<ConfigurationForm projectId={projectId} onClose={()=>setShowForm(false)} onSaved={async()=>{setShowForm(false);await refresh();}}/>:null}{error?<div className={styles.runError}>{error}</div>:null}<ExecutionOutput execution={latest}/></div>;
}

function ConfigurationForm({projectId,onClose,onSaved}:{projectId:string;onClose():void;onSaved():Promise<void>}){const[name,setName]=useState(""),[command,setCommand]=useState(""),[args,setArgs]=useState(""),[working,setWorking]=useState("."),[saving,setSaving]=useState(false);async function save(){if(!name.trim()||!command.trim())return;setSaving(true);const response=await fetch(`${serverUrl}/api/projects/${projectId}/run-configurations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),command:command.trim(),arguments:args.split("\n").map(value=>value.trim()).filter(Boolean),workingDirectory:working.trim()||"."})});setSaving(false);if(response.ok)await onSaved();}return <div className={styles.runForm}><header><strong>New run configuration</strong><button onClick={onClose}><X/></button></header><label>Name<input value={name} onChange={event=>setName(event.target.value)} placeholder="Development server"/></label><label>Executable<input value={command} onChange={event=>setCommand(event.target.value)} placeholder="npm"/></label><label>Arguments · one per line<textarea value={args} onChange={event=>setArgs(event.target.value)} placeholder={"run\ndev"}/></label><label>Working directory<input value={working} onChange={event=>setWorking(event.target.value)} placeholder="."/></label><footer><button onClick={onClose}>Cancel</button><button className={styles.runPrimary} disabled={saving||!name.trim()||!command.trim()} onClick={()=>void save()}>Save</button></footer></div>}
function ExecutionOutput({execution}:{execution?:Execution}){const output=useMemo(()=>execution?stripAnsi([execution.stdout,execution.stderr].filter(Boolean).join("\n")):"",[execution]);return <div className={styles.runOutput}>{execution?<><header><span className={`${styles.executionState} ${styles[`execution_${execution.status}`]??""}`}/><strong>{execution.command} {execution.arguments.join(" ")}</strong><small>{execution.status}{execution.exitCode!==null?` · exit ${execution.exitCode}`:""}</small></header><pre>{output||execution.error||"Command started. Waiting for output…"}</pre></>:<div><strong>No executions yet</strong><span>Choose a configuration and run it. Output will appear here.</span></div>}</div>}
// eslint-disable-next-line no-control-regex
const stripAnsi=(value:string)=>value.replace(/\x1B(?:[@-_]|\[[0-?]*[ -/]*[@-~])/g,"");
